x-sharedConfig: &sharedConfig
  logging:
    driver: "json-file"
    options:
      max-size: "500k"
      max-file: "10"

x-sharedDeployConfig: &sharedDeployConfig
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
        reservations:
          cpus: '0.1'
          memory: 5M

version: "3.4"

services:
  remote-api:
    <<: *sharedConfig
    build: . 
    ports:
     - "${PORT}:443"
    environment:
     - CREATE_CERTS_WITH_PW=${CREATE_CERTS_WITH_PW}
     - CERT_HOSTNAME=${CERT_HOSTNAME}
     - CERT_EXPIRATION_DAYS=${CERT_EXPIRATION_DAYS}
    volumes:
     - "${CERT_PATH}:/data/certs"
     - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      <<: *sharedDeployConfig
      placement:
        constraints:
          - node.role == manager
